### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by Aternans** [JumpJets/Archive-mangalib-userscript#1]
При нажатии на кнопку ничего не происходит.
Браузер - Opera GX
Абсолютно идентичная проблема со скриптом для ранобелиба.

**Comment by XCanG** [comment]
Скрипт не обновлялся с апреля 2022, есть шанс что сайт переделали и он отпал.

**Comment by XCanG** [comment]
Глянул подробнее, скрипт в целом рабочий _(можно лишь немного освежить)_, но там другой домен с которого CORS не проходит и не даёт скачать картинки (к примеру `img2.mixlib.me`). Часть при этом качается (к примеру `img33.imgslib.link`).

Не уверен если на стороне браузера получится обойти ошибки CORS'а.
